### PR TITLE
fix all configs & dependencies

### LINKED ISSUE #29: fix eslint config
the eslint seems not to work corectly

### PR DESCRIPTION
**Pull request by Lucimad007**
- remove eslint extra dependency
- use eslintrc.json config file
- remove useless tailwind css config file
- update dependencies
- update gitignore file (.idea)
- update lintstaged commands
- add .prettierrc rules
- remove eslint.config.mjs

### CODE REVIEW

File: src/components/navbar/searchbar.tsx [hunk 1]
```diff
@@ -1,60 +1,46 @@
...
 
   return (
     <div
-      className={`
-      flex items-center justify-between w-[672px] h-[56px] p-3 
-      bg-white dark:bg-green-ergo-navbar rounded-3xl 
-      transition-all duration-300 ease-linear dark:shadow-black shadow-md
-      ${isFocused ? "ring-2 ring-blue-400 dark:ring-yellow-ergo-navbar" : "shadow-gray-500/50"}
-    `}
+      className={`dark:bg-green-ergo-navbar flex h-[56px] w-[672px] items-center justify-between rounded-3xl bg-white p-3 shadow-md transition-all duration-300 ease-linear dark:shadow-black ${isFocused ? 'dark:ring-yellow-ergo-navbar ring-2 ring-blue-400' : 'shadow-gray-500/50'} `}
```
Comment (zargarzadehm) [inline src/components/navbar/searchbar.tsx]: Check line length rules and fix it!

Comment (Lucimad007) [reply src/components/navbar/searchbar.tsx]: done
