### PR TITLE
Fix/125 fix token links

### LINKED ISSUE #125: fix token links
- fix token links to open the correct URL
- make the whole asset be a link to the corresponding token

### PR DESCRIPTION
**Pull request by Lucimad007**

### CODE REVIEW

File: src/configs/index.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-export const ExplorerURL = process.env.EXPLORER_URL;
+export const TokenExplorerURL = process.env.NEXT_PUBLIC_TOKEN_EXPLORER_URL;
```
Comment (zargarzadehm) [inline src/configs/index.ts]: fix base token url

**Review by zargarzadehm — CHANGES_REQUESTED** [review]

File: src/configs/index.ts (hunk 1 above)
Comment (Lucimad007) [reply src/configs/index.ts]: fixed

**Review by zargarzadehm — APPROVED** [review]
